---
- name: Configure standard ACL
  hosts: R2
  gather_facts: false
  connection: network_cli
 
  tasks:
    - name: Load new ACL into device
      ios_config:
        parents: ip access-list extended REQ1
        lines:
          - 10 deny tcp any any eq telnet
          - 20 permit ip any any
                  
    - name: Apply new ACL to R2 Eth0/1 out
      ios_config:
        parents: interface Ethernet0/1 out
        lines:
          - ip access-group REQ1 out

    - name: Check applied ACL on interface Ethernet0/1
      ios_command:
        commands:
          - show ip access-lists REQ1
          - show run interface Ethernet0/1
      register: acl_results

    - name: Display ACL and interface configuration
      debug:
        msg: |
          Results of applied ACL on interface Ethernet0/1:
          {{ acl_results.stdout }}