---
- name: Configure standard ACL
  hosts: 10.0.0.2
  gather_facts: false
  connection: network_cli
 
  tasks:
    - name: Load new ACL into device
      ios_config:
        parents: ip access-list extended REQ1
        lines:
          - deny tcp any any eq telnet
          - permit ip any any
                  
    - name: Apply new ACL to R2 Eth0/1 out
      ios_config:
        parents: interface Ethernet0/1
        lines:
          - ip access-group REQ1 out
      tags:
        - apply_acl_e0/1

    - name: Check applied ACL on interface Ethernet0/1
      ios_command:
        commands:
          - show ip access-lists REQ1
          - show run interface Ethernet0/1
      register: acl_results
      tags:
        - check_acl

    - name: Display ACL and interface configuration
      debug:
        msg: |
          Results of applied ACL on interface Ethernet0/1:
          {{ acl_results.stdout }}
      tags:
        - display_results